#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
wal -i $HOME/Pictures/.wallpaper.png &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#1793D1
bspc config normal_border_color \#1F1F1F

~/.config/polybar/launch.sh --shapes
xbindkeys --poll-rc
picom
